### ISSUE TITLE
Installing with Quicklisp

### ISSUE THREAD

**Issue by slimetree** [malisper/Clamp#2]
I tried doing this:

    (ql:quickload :clamp)

    debugger invoked on a LOAD-SYSTEM-DEFINITION-ERROR:
      Error while trying to load definition for system clamp from pathname
      /Users/bh/quicklisp/local-projects/Clamp/clamp.asd:
         The name "ASDF-USER" does not designate any package.

Any ideas?

**Comment by malisper** [comment]
I have a couple of ideas.

From the error message it appears that asdf has not been loaded. The first thing I suggest doing would be to use (ql:quickload :asdf) and then try to load clamp. Also try (require :asdf).

If neither of those things work, you should try to load Clamp purely from ASDF. Follow the instructions from [here](https://common-lisp.net/project/asdf/asdf.html) , mainly sections 3.3, 4.1 and 5.1.

If none of the above works, I would suggest contacting the maintainers of Quicklisp and/or the maintainers of ASDF.

**Comment by slimetree** [comment]
I got it working. I just installed ccl instead of clisp/sbcl. I don't know
why that worked. I'm on OSX so maybe the brew package was messed up.

**Comment by vindarel** [comment]
Hi ! But clamp isn't on Quicklisp, right ? (http://quickdocs.org/clamp/ = 404) That's such a shame, clamp looks like the lisp I've been wating for ! :) Any plans ?

**Comment by malisper** [comment]
No plans to put clamp on Quicklisp. I haven't done much CL programming in the past year and a half. You can still load Clamp using Quicklisp if you have installed Clamp locally.
